### ISSUE TITLE
VSCode extension dependency interface update

### ISSUE THREAD

**Issue by sfoslund** [Naninovel/VSCode#2]
https://github.com/dotnet/vscode-dotnet-runtime (the VSCode extension you're relying on to install the .NET runtime) has updated its acquisition interface, see:
https://github.com/dotnet/vscode-dotnet-runtime/blob/master/vscode-dotnet-runtime-library/src/IDotnetAcquireContext.ts.

Your current implementation won't break but your users won't get access to our new manual install feature unless you include the requestingExtensionId (this extension's ID) in the acquire calls you make. We have seen some customer complaints about this on our repo: https://github.com/dotnet/vscode-dotnet-runtime/issues/139#issuecomment-727142594

**Comment by Elringus** [comment]
@sfoslund Thank you for letting us know!
