### ISSUE TITLE
IDE error

### ISSUE THREAD

**Issue by GZone19** [Naninovel/VSCode#3]
Does this occur consistently? 
Repro steps:

1.
2.

Action: naniscript.activate
Error type: Error
Error Message: Failed to install .NET runtime v3.1.

Version: 1.3.1
OS: win32
OS Release: 10.0.18363
Product: Visual Studio Code
Product Version: 1.53.2
Language: en

<details>
<summary>Call Stack</summary>

```
client.js:70:19client.js:70:19
fulfilled client.js:5:58
```

</details>

**Comment by Elringus** [comment]
Hey, I've answered on the Discord support.
